game/urls.py
from django.urls import path
from . import views

app_name = 'game'
urlpatterns = [
        path('w/<int:pk>', views.WarProfile.as_view(), name='warprofile'),
        path('army/<int:userid>', views.army, name='army')
]

mygame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls'))
]

game/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Warrior(models.Model):
    name = models.CharField(max_length=32)
    hp = models.IntegerField(default=100)
    ap = models.FloatField(default=10.0)
    dp = models.FloatField(default=0.1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return '{} ({})'.format(self.name, self.user)

game/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.views import generic
from .models import Warrior

# Create your views here.

class WarProfile(generic.DetailView):
    model = Warrior

def army(request, userid):
    user = get_object_or_404(User, pk=userid)
    warriors = Warrior.objects.filter(user=user)
    context = {
            'user': user,
            'warriors': warriors
            }
    return render(request, 'game/army.html', context)

game/templates/game/army.html
<HTML>
	<head>
		<title>
			My Game
		</title>
	</head>
	<body>
		<h1>
			{{ user.username }}`s army
		</h1>
        {% if warriors %}
          <h2>Warriors:</h2>
          <ul>
              {% for warrior in warriors %}
              <li><a href="{% url 'game:warprofile' warrior.pk %}">{{ warrior.name }}</a></li>
              {% endfor %}
          </ul>
        {% else %}
          <p>No warriors for {{ user.username }}</p>
        {% endif %}
	</body>
</HTML>

game/templates/game/warrior_detail.html
<HTML>
	<head>
		<title>
			My Game
		</title>
	</head>
	<body>
		<h1>
			{{ warrior.name }}
		</h1>
		<p>health: {{ warrior.hp }}</p>
		<p>Attack: {{ warrior.ap }}</p>
		<p>Defence: {{ warrior.dp }}</p>
	</body>
</HTML>